
import React, { useState } from 'react';
import { AuditReport } from '../types';
import ReactMarkdown from 'react-markdown';
import { CheckCircle, AlertTriangle, FileText, Download, Share2, ChevronLeft } from 'lucide-react';

interface ReportManagerProps {
  reports: AuditReport[];
}

export const ReportManager: React.FC<ReportManagerProps> = ({ reports }) => {
  const [selectedReport, setSelectedReport] = useState<AuditReport | null>(null);

  if (selectedReport) {
    return (
      <div className="h-full flex flex-col bg-slate-900 rounded-xl border border-slate-700/50 overflow-hidden animate-in slide-in-from-right duration-300">
        {/* Report Toolbar */}
        <div className="p-4 border-b border-slate-700/50 bg-slate-800/50 flex justify-between items-center">
          <button 
            onClick={() => setSelectedReport(null)}
            className="flex items-center gap-2 text-sm text-slate-400 hover:text-white transition-colors"
          >
            <ChevronLeft className="w-4 h-4" /> Back to List
          </button>
          <div className="flex gap-2">
            <button className="px-3 py-1.5 bg-slate-700 hover:bg-slate-600 rounded text-xs font-bold text-white flex items-center gap-2">
              <Download className="w-3 h-3" /> PDF
            </button>
            <button className="px-3 py-1.5 bg-indigo-600 hover:bg-indigo-500 rounded text-xs font-bold text-white flex items-center gap-2">
              <Share2 className="w-3 h-3" /> Share Certificate
            </button>
          </div>
        </div>

        {/* Report Content */}
        <div className="flex-grow overflow-y-auto custom-scrollbar p-8 bg-white text-slate-900">
          <div className="max-w-3xl mx-auto">
             <div className="border-b-2 border-slate-100 pb-6 mb-6 flex justify-between items-start">
               <div>
                 <h1 className="text-3xl font-black text-slate-900 mb-2">Audit Report</h1>
                 <div className="text-slate-500 text-sm">Generated by Talos Infrastructure</div>
               </div>
               <div className="text-right">
                 <div className="text-sm text-slate-400 font-mono">{selectedReport.timestamp}</div>
                 <div className="text-sm font-bold text-indigo-600">{selectedReport.projectName}</div>
               </div>
             </div>

             <div className="grid grid-cols-3 gap-4 mb-8">
                <div className="bg-slate-50 p-4 rounded-lg border border-slate-100 text-center">
                  <div className="text-xs text-slate-500 uppercase tracking-wide">Risk Score</div>
                  <div className={`text-3xl font-black ${selectedReport.riskScore > 80 ? 'text-emerald-600' : 'text-red-500'}`}>
                    {selectedReport.riskScore}
                  </div>
                </div>
                <div className="bg-slate-50 p-4 rounded-lg border border-slate-100 text-center">
                  <div className="text-xs text-slate-500 uppercase tracking-wide">Issues Found</div>
                  <div className="text-3xl font-black text-slate-800">{selectedReport.issuesFound}</div>
                </div>
                <div className="bg-slate-50 p-4 rounded-lg border border-slate-100 text-center">
                  <div className="text-xs text-slate-500 uppercase tracking-wide">Status</div>
                  <div className="text-xl font-bold text-emerald-600 mt-1">Verified</div>
                </div>
             </div>

             <div className="prose max-w-none prose-headings:font-bold prose-h2:text-indigo-900 prose-h3:text-slate-800 prose-pre:bg-slate-900 prose-pre:text-slate-50">
               <ReactMarkdown>{selectedReport.fullReportMarkdown}</ReactMarkdown>
             </div>

             <div className="mt-12 pt-8 border-t border-slate-100 text-center text-slate-400 text-sm">
                <p>Secured by Talos. This report does not constitute a guarantee of security.</p>
             </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto space-y-6">
       <div className="flex justify-between items-center">
         <h2 className="text-xl font-bold text-white">Generated Reports</h2>
         <div className="text-sm text-slate-400">Total Reports: {reports.length}</div>
       </div>

       {reports.length === 0 ? (
         <div className="bg-slate-800/50 rounded-xl border border-slate-700/50 p-12 text-center">
            <FileText className="w-16 h-16 text-slate-600 mx-auto mb-4" />
            <h3 className="text-lg font-bold text-slate-300">No Reports Yet</h3>
            <p className="text-slate-500">Run the scanner to generate your first audit certificate.</p>
         </div>
       ) : (
         <div className="grid gap-4">
           {reports.map(report => (
             <div 
               key={report.id} 
               onClick={() => setSelectedReport(report)}
               className="bg-slate-800/50 hover:bg-slate-700/50 border border-slate-700/50 rounded-xl p-6 cursor-pointer transition-all group"
             >
               <div className="flex justify-between items-center">
                 <div className="flex items-center gap-4">
                    <div className={`p-3 rounded-lg ${report.issuesFound > 0 ? 'bg-red-500/20 text-red-400' : 'bg-emerald-500/20 text-emerald-400'}`}>
                      {report.issuesFound > 0 ? <AlertTriangle className="w-6 h-6" /> : <CheckCircle className="w-6 h-6" />}
                    </div>
                    <div>
                      <h3 className="font-bold text-slate-200 group-hover:text-indigo-300 transition-colors">
                        {report.fileName}
                      </h3>
                      <p className="text-sm text-slate-500">{report.summary.substring(0, 80)}...</p>
                    </div>
                 </div>
                 <div className="text-right">
                    <div className="text-2xl font-bold text-white">{report.riskScore}</div>
                    <div className="text-[10px] text-slate-500 uppercase">Score</div>
                 </div>
               </div>
             </div>
           ))}
         </div>
       )}
    </div>
  );
};